=== Juan0987654321/Tasques-LMG/Tasca Avaluable LMSGI04.1/cataleg.dtd
<!ELEMENT cataleg (single | album)*>

<!ELEMENT single (titol, descripcio?, pais, idioma, genere*, grup, membres, durada)>
<!ATTLIST single codi CDATA #REQUIRED>


<!ELEMENT album (titol, descripcio?, pais, idioma, genere*, grup, membres, numero_cancons, titols_cancons)>
<!ATTLIST album codi CDATA #REQUIRED>


<!ELEMENT titol (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>

<!ELEMENT genere (classica |jazz|blues|gospel|soul|pop|rock_and_roll|country)>
<!ELEMENT classica EMPTY>
<!ELEMENT jazz EMPTY>
<!ELEMENT blues EMPTY>
<!ELEMENT gospel EMPTY>
<!ELEMENT soul EMPTY>
<!ELEMENT pop EMPTY>
<!ELEMENT rock_and_roll EMPTY>
<!ELEMENT country EMPTY>

<!ELEMENT grup (#PCDATA)>


<!ELEMENT membres (membre+)>
<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>
<!ELEMENT nom (#PCDATA)>


<!ELEMENT durada (#PCDATA)>


<!ELEMENT numero_cancons (#PCDATA)>
<!ELEMENT titols_cancons (canco+)>
<!ELEMENT canco (titol_canco, durada_canco)>
<!ATTLIST canco numero CDATA #REQUIRED>

<!ELEMENT titol_canco (#PCDATA)>
<!ELEMENT durada_canco (#PCDATA)>

=== Juan0987654321/Tasques-LMG/Tasca Avaluable LMSGI04.1/4.1cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">

<cataleg>

    <single codi="S001">
        <titol>Imagine</titol>
        <descripcio>Single famós de John Lennon</descripcio>
        <pais>Regne Unit</pais>
        <idioma>Anglès</idioma>
        <genere><pop/></genere>
        <grup>John Lennon</grup>
        <membres>
            <membre sexe="home">
                <nom>John Lennon</nom>
            </membre>
        </membres>
        <durada>3.1</durada>
    </single>

    <single codi="S002">
        <titol>Halo</titol>
        <pais>Estats Units</pais>
        <idioma>Anglès</idioma>
        <genere><pop/></genere>
        <genere><soul/></genere>
        <grup>Beyoncé</grup>
        <membres>
            <membre sexe="dona">
                <nom>Beyoncé Knowles</nom>
            </membre>
        </membres>
        <durada>4.2</durada>
    </single>

 
    <album codi="A001">
        <titol>Thriller</titol>
        <descripcio>Àlbum més venut de Michael Jackson</descripcio>
        <pais>Estats Units</pais>
        <idioma>Anglès</idioma>
        <genere><pop/></genere>
        <genere><soul/></genere>
        <grup>Michael Jackson</grup>
        <membres>
            <membre sexe="home">
                <nom>Michael Jackson</nom>
            </membre>
        </membres>
        <numero_cancons>2</numero_cancons>
        <titols_cancons>
            <canco numero="1">
                <titol_canco>Thriller</titol_canco>
                <durada_canco>5.57</durada_canco>
            </canco>
            <canco numero="2">
                <titol_canco>Beat It</titol_canco>
                <durada_canco>4.18</durada_canco>
            </canco>
        </titols_cancons>
    </album>

    <album codi="A002">
        <titol>25</titol>
        <pais>Regne Unit</pais>
        <idioma>Anglès</idioma>
        <genere><pop/></genere>
        <grup>Adele</grup>
        <membres>
            <membre sexe="dona">
                <nom>Adele Adkins</nom>
            </membre>
        </membres>
        <numero_cancons>2</numero_cancons>
        <titols_cancons>
            <canco numero="1">
                <titol_canco>Hello</titol_canco>
                <durada_canco>4.55</durada_canco>
            </canco>
            <canco numero="2">
                <titol_canco>Send My Love</titol_canco>
                <durada_canco>3.43</durada_canco>
            </canco>
        </titols_cancons>
    </album>

</cataleg>
