=== Juan0987654321/Tasques-LMG/Tasca Avaluable LMSGI04.4/cifp.dtd
<!ELEMENT cifp (alumne | professor)*>

<!ELEMENT alumne (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_matricula, curs)>
<!ATTLIST alumne id NMTOKEN #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT llinatges (#PCDATA)>
<!ELEMENT data_naixement (#PCDATA)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT data_matricula (#PCDATA)>
<!ELEMENT curs (#PCDATA)>

<!ELEMENT professor (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_incorporació, departament, assignatura*)>
<!ATTLIST professor id NMTOKEN #REQUIRED>

<!ELEMENT data_incorporació (#PCDATA)>
<!ELEMENT departament (#PCDATA)>

<!ELEMENT assignatura (nom_assignatura, data_inici?, data_final?)>
<!ATTLIST assignatura id_assignatura NMTOKEN #REQUIRED>

<!ELEMENT nom_assignatura (#PCDATA)>
<!ATTLIST nom_assignatura cicle (DAM|DAW|ASIX|SMX|SEIA|ER|AUT) #REQUIRED>

=== Juan0987654321/Tasques-LMG/Tasca Avaluable LMSGI04.4/exercici1_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">
<cifp>
    <alumne id="1">
        <nom>Joan</nom>
        <llinatges>García</llinatges>
        <data_matricula>2023-09-01</data_matricula>
        <curs>DAM</curs>
    </alumne>
    <professor id="100">
        <nom>Marta</nom>
        <llinatges>Sastre</llinatges>
        <data_incorporació>2010-01-15</data_incorporació>
        <departament>Informàtica</departament>
        <assignatura id_assignatura="50">
            <nom_assignatura cicle="DAW">Programació Web</nom_assignatura>
        </assignatura>
    </professor>
</cifp>
